[package]
name = "ras"
version = "0.1.0"
edition = "2021"
description = "A toy assembler."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.40"

[dev-dependencies]
anyhow = "1.0.71"
pretty_assertions = "1.3.0"
